project:
  type: website
  output-dir: docs

site:
  title: "Software R para aplicações em IA"
  subtitle: "Uma Abordagem Prática"
  author:
    - name: "Anderson Castro Soares de Oliveira"
      affiliations:
        - name: "Departamento de Estatística/UFMT"
    - name: "João Pedro Florentino de Oliveira Nascimento"
      affiliations:
        - name: "Departamento de Estatística/UFMT"
  favicon: imagens/Eri-Logo.jpg
  logo: imagens/Eri-Logo.jpg
  date: "11/23/2023"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Capítulo 1"
        href: cap1.qmd
      - text: "Capítulo 2"
        href: cap2.qmd
      - text: "Capítulo 3"
        href: cap3.qmd
      - text: "Capítulo 4"
        href: cap4.qmd
      - text: "Capítulo 5"
        href: cap5.qmd
  sections:
    - home: index.qmd
    - capítulo 1: cap1.qmd
    - capítulo 2: cap2.qmd
    - capítulo 3: cap3.qmd
    - capítulo 4: cap4.qmd
    - capítulo 5: cap5.qmd

bibliography: references.bib
format:
  html:
    theme:
      - cosmo
      - r4ds.scss
    highlight-style: tango
    toc: true
    code-link: true

editor: visual
